### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by Nuckal777** [flatcar-linux/flatcar-linux-update-operator#89]
Hello :wave:,

a lot of work has been done since the last release, which was 1,5 years ago, and it would be great if those bug fixes and features would reach us users.

**Comment by invidian** [comment]
Hey, thanks for creating the issue. It's been a while since the last release indeed.

However, there has been almost no bug fixes or features implemented since the last release. There has been _a lot_ of internal changes though. My initial idea was to complete all issues in [v0.8.0](https://github.com/flatcar-linux/flatcar-linux-update-operator/milestone/2) milestone, however that may still take some time.

I guess we could release early just with Go, Alpine and Go dependencies updates at least.

**Comment by Nuckal777** [comment]
Updated dependencies would certainly be good. Moreover, it would be great if b569ef3d2369d6a2a56995cb02663739223c2b3e could also make into a release, which fixes a crash when the agent is trying to update a node's schedulable value while that node is modified by something else. :boom: It caused a bit trouble while creating E2E tests for https://github.com/sapcc/maintenance-controller.

**Comment by invidian** [comment]
Oh, thanks for the insights @Nuckal777, it's really really valuable!

I'll try to make some release then.

**Comment by invidian** [comment]
I'm working on getting an RC release soon.

**Comment by invidian** [comment]
Soo, I've created an [v0.8.0-rc1](https://github.com/flatcar-linux/flatcar-linux-update-operator/releases/tag/v0.8.0-rc1), if someone wants to test it. I'll wait for some feedback and then I will release v0.8.0.

**Comment by Nuckal777** [comment]
I gave it a shot and the issue I mentioned is gone. Otherwise the agent seems to work fine. Thanks.

**Comment by invidian** [comment]
Slightly behind the schedule, but https://github.com/flatcar-linux/flatcar-linux-update-operator/releases/tag/v0.8.0 is now out :tada:
